sudo: required
env:
  - _FORCE_LOGS=1
language:
  - objective-c
osx_image: xcode7.3
git: # Handle git submodules yourself
  submodules: false
node_js:
  - "0.12"
before_install:
  # Use sed to replace the SSH URL with the public URL, then initialize submodules
  # code from http://stackoverflow.com/a/24600210/375688
  - sed -i '' 's/git@github.com:/https:\/\/github.com\//' /Users/travis/build/appium/appium-xcuitest-driver/.gitmodules
  - git submodule update --init --recursive
  - brew install carthage
  - pushd WebDriverAgent && ./Scripts/bootstrap.sh && popd
before_script:
  - rvm get head
  - npm install
  - npm install -g gulp
  - npm install -g mocha
#  - gulp transpile we don't need to transpile here since `gulp test` runs transpilation
script:
  - gulp eslint
  - gulp once
  - gulp e2e-test
  - gulp coveralls
